name = "open-same"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "open-same-prod"
# TODO: Replace with your production domain
route = "your-domain.com/*"

[env.staging]
name = "open-same-staging"
# TODO: Replace with your staging domain
route = "staging.your-domain.com/*"

[build]
command = "npm run build"
cwd = "frontend"

[build.upload]
format = "directory"
dir = "frontend/dist"

[site]
bucket = "frontend/dist"

[env.production.vars]
ENVIRONMENT = "production"
# TODO: Replace with your production backend API URL
API_URL = "https://your-backend-api.com"

[env.staging.vars]
ENVIRONMENT = "staging"
# TODO: Replace with your staging backend API URL
API_URL = "https://staging-backend-api.com"

# Functions (if you want to add serverless functions)
[functions]
directory = "functions"

# KV Namespaces (if you need key-value storage)
# [[kv_namespaces]]
# binding = "CONTENT_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects (if you need real-time features)
# [[durable_objects.bindings]]
# name = "COLLABORATION_HUB"
# class_name = "CollaborationHub"

# R2 Storage (if you need file storage)
# [[r2_buckets]]
# binding = "FILE_STORAGE"
# bucket_name = "your-r2-bucket-name"