name: Quick Deploy to Cloudflare Pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      force_rebuild:
        description: 'Force rebuild all components'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'
  GO_VERSION: '1.21'

jobs:
  quick-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Setup Wrangler CLI
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
    - name: Deploy to Cloudflare Pages
      run: |
        if [ "${{ github.event.inputs.environment }}" == "production" ]; then
          PROJECT_NAME="open-same"
          BRANCH="main"
        else
          PROJECT_NAME="open-same-staging"
          BRANCH="develop"
        fi
        
        wrangler pages deploy frontend/dist \
          --project-name=$PROJECT_NAME \
          --branch=$BRANCH \
          --env=${{ github.event.inputs.environment }}
    
    - name: Deployment Summary
      run: |
        echo "## 🚀 Quick Deploy Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "**Force rebuild:** ${{ github.event.inputs.force_rebuild }}" >> $GITHUB_STEP_SUMMARY
        echo "**Deployment time:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ What was deployed:" >> $GITHUB_STEP_SUMMARY
        echo "- Frontend React application" >> $GITHUB_STEP_SUMMARY
        echo "- Same.AI replica features" >> $GITHUB_STEP_SUMMARY
        echo "- Real-time collaboration system" >> $GITHUB_STEP_SUMMARY
        echo "- User authentication" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Next steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Verify deployment at your Cloudflare Pages URL" >> $GITHUB_STEP_SUMMARY
        echo "2. Test key functionality" >> $GITHUB_STEP_SUMMARY
        echo "3. Monitor for any issues" >> $GITHUB_STEP_SUMMARY